name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: cd src && make
    - name: make check
      id: test
      run: cd src && make check
    - name: Check Tests Passed
      if: steps.test.outputs.result != 0
      run: exit 1
